name: Appium Tests

on:
  push:
    branches: [main]


jobs:
  browserstack-appium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven Dependencies
        run: mvn install -DskipTests

      - name: Run Appium Tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          mvn test -Dbs.user=$BROWSERSTACK_USERNAME -Dbs.key=$BROWSERSTACK_ACCESS_KEY
